### ISSUE TITLE
signup 할때 email과 password를 검사하지 않는 현상

### ISSUE THREAD

**Issue by sskim0126** [ReallyView/server#35]
현재 email과 password가 적당한지 판단하는 기준이 없어서 빈 문자열을 집어넣어도 signup이 됨
email은 email 형식을 갖추었는지, password는 자릿수 등을 판단하는 기준을 세울 필요가 있음

**Comment by Acasia** [comment]
ㅇㅋㅇㅋ추가할게 클라이언트에서도 signup할때 명시를 해줘, password는 몇자이상으로 정해야하는지
